In [1]:
import time
import numpy as np

In [ ]:
# Using Pyhton lists
start_time = time.time()

py_list = list(range(10**8))
py_sum = sum(py_list)

end_time = time.time()

execution_time_py = end_time - start_time
print("Python list execution time:", execution_time_py)

Python list execution time: 4.764940977096558


In [6]:
# Using NumPy arrays
start_time = time.time()

np_array = np.arange(10**8) # Create a NumPy array with 100 million elements
np_sum = np.sum(np_array)

end_time = time.time()
execution_time_np = end_time - start_time
print("NumPy execution time: ", execution_time_np)

NumPy execution time:  0.2855978012084961


In [7]:
print(f"NumPy was {execution_time_py / execution_time_np:.2f}x fastet, powerfull numpy")

NumPy was 16.68x fastet, powerfull numpy


In [8]:
# Memory usage
np_memory = np_array.nbytes
py_memory = sum(i.__sizeof__() for i in py_list)

print("NumPy memory usage: ", np_memory)
print("Python list memory usage: ", py_memory)


NumPy memory usage:  800000000
Python list memory usage:  2800000000


In [9]:
print(f"NumPy's used {py_memory / np_memory}x times less memory")

NumPy's used 3.5x times less memory


Numpy Array

In [11]:
import numpy as np

# Creating array from a list
arr1 = np.array([1, 2, 3]) # or np.array((1, 2, 3))

type(arr1) # n dimensional array
print(arr1)

[1 2 3]


In [13]:
arr2 = np.array([[1, 2, 3], [5, 0, 9]])
arr2

array([[1, 2, 3],
       [5, 0, 9]])

In [ ]:
# creating empty array

empty = np.empty((2, 3, 4)) # random values
print(empty)

# creating array with constant values
full = np.full((2, 3), 7)
print(full)



[[[4.67296746e-307 1.69121096e-306 1.29060871e-306 1.89146896e-307]
  [7.56571288e-307 4.00544531e-307 1.11261095e-306 3.56043054e-307]
  [1.37961641e-306 2.22518251e-306 1.33511969e-306 6.23037996e-307]]

 [[9.34609790e-307 8.45593934e-307 9.34600963e-307 3.56036603e-307]
  [1.37961641e-306 1.37961302e-306 1.11259940e-306 1.60219035e-306]
  [1.11261570e-306 1.06811354e-306 8.34448533e-308 1.69105613e-306]]]
[[7 7 7]
 [7 7 7]]


boolean indexing/masking

In [18]:
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

In [19]:
a = [1, 2, 3, 4, 5]
print([i for i in a if i>= 4])
a

[4, 5]


[1, 2, 3, 4, 5]

In [23]:
a = np.array(a)
a >= 4

# a[a >= 4]

array([False, False, False,  True,  True])

In [25]:
two_dim_array = np.array([[1, 2, 3],
                          [4, 5, 6],
                          [7, 8, 9]])

print("\nOriginal 2D array:")
print(two_dim_array)

# Boolean indexing in a 2D array - let's select elements greater than 5
print("\nElements greater than 5:")

print(two_dim_array > 5)
print(two_dim_array[two_dim_array > 5])


Original 2D array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Elements greater than 5:
[[False False False]
 [False False  True]
 [ True  True  True]]
[6 7 8 9]


In [27]:
one_dim_array = np.arange(1, 16)

# Reshaping a 1D array to a 2D array
two_dim_array = one_dim_array.reshape((5, 3))

print("\nReshaped 2D array:")
print(two_dim_array)

# Reshaping a 1D array to a 2D array
two_dim_array = one_dim_array.reshape((5, -1))
print(two_dim_array)


Reshaped 2D array:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [28]:
print(two_dim_array)
# Transposing a 2D array
transposed_array = two_dim_array.T

print("\nTransposed 2D array:")
print(transposed_array)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]

Transposed 2D array:
[[ 1  4  7 10 13]
 [ 2  5  8 11 14]
 [ 3  6  9 12 15]]


In [29]:
print(two_dim_array)
# Flattening a 2D array to a 1D array
flattened_array = two_dim_array.flatten()

print("\nFlattened 1D array:")
print(flattened_array)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]

Flattened 1D array:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [31]:
import numpy as np

# Create two 2D arrays
array_1 = np.array([[1, 2], [3, 4]])
array_2 = np.array([[5, 6], [7, 8]])

array_3 = np.array([[5, 6, 7], [7, 8, 9]])

print("Original arrays:")
print("Array 1:")
print(array_1)
print("\nArray 2:")
print(array_2)

# Exponential and logarithmic operations
print(array_1)

print("\nExponential values of array 1:")
print(np.exp(array_1))

print("\nNatural logarithm values of array 1:")
print(np.log(array_1))

print("\nBase 10 logarithm values of array 1:")
print(np.log10(array_1))

print("\nBase 2 logarithm values of array 1:")
print(np.log2(array_1))

Original arrays:
Array 1:
[[1 2]
 [3 4]]

Array 2:
[[5 6]
 [7 8]]
[[1 2]
 [3 4]]

Exponential values of array 1:
[[ 2.71828183  7.3890561 ]
 [20.08553692 54.59815003]]

Natural logarithm values of array 1:
[[0.         0.69314718]
 [1.09861229 1.38629436]]

Base 10 logarithm values of array 1:
[[0.         0.30103   ]
 [0.47712125 0.60205999]]

Base 2 logarithm values of array 1:
[[0.        1.       ]
 [1.5849625 2.       ]]


In [32]:
# Create two 1D arrays
array_1 = np.array([1, 2, 3])
array_2 = np.array([4, 5, 6])

print("Original arrays:")
print("Array 1:", array_1)
print("Array 2:", array_2)

Original arrays:
Array 1: [1 2 3]
Array 2: [4 5 6]


In [33]:
# Concatenation
concatenated_array = np.concatenate((array_1, array_2))
print("\nConcatenated array:")
print(concatenated_array)

array_2d_1 = np.array([[1, 2, 3], [4, 5, 6]])
array_2d_2 = np.array([[7, 8, 9], [10, 11, 12]])

# Concatenation of 2D arrays
concatenated_2d_array = np.concatenate((array_2d_1, array_2d_2), axis=1)  # Concatenate along rows
print(concatenated_2d_array)


Concatenated array:
[1 2 3 4 5 6]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [34]:
# իրար վրա դնել
vertical_stack = np.vstack((array_1, array_2))
print("\nVertically stacked array:")
print(vertical_stack)

# իրար կողք դնել
horizontal_stack = np.hstack((array_1, array_2))
print("\nHorizontally stacked array:")
print(horizontal_stack)


Vertically stacked array:
[[1 2 3]
 [4 5 6]]

Horizontally stacked array:
[1 2 3 4 5 6]


In [35]:
# Splitting - Divide an array into multiple sub-arrays
array = np.array([1, 2, 3, 4, 5, 6])
split_arrays = np.split(array, 3)
print("\nSplit arrays:")
print(split_arrays)


Split arrays:
[array([1, 2]), array([3, 4]), array([5, 6])]


In [36]:
# Create an array
array = np.array([1, 2, 3, 1, 2, 4, 5, 4])

print("Original array:")
print(array)

# Finding unique elements
unique_elements = np.unique(array)
print("\nUnique elements:")
print(unique_elements)

# Counting occurrences of each unique element
unique_values, value_counts = np.unique(array, return_counts=True)
print("\nUnique values:")
print(unique_values)
print("Value counts:")
print(value_counts)

Original array:
[1 2 3 1 2 4 5 4]

Unique elements:
[1 2 3 4 5]

Unique values:
[1 2 3 4 5]
Value counts:
[2 2 1 2 1]


In [37]:
# Reversing the order of elements
array = np.array([1,2,3,4,5])
print("original")
print(array)
reversed_array = np.flip(array) # [::-1] .reverse
print("\nReversed array:")
print(reversed_array)


# Shuffling the array
np.random.shuffle(array)
print("\nShuffled array:")
print(array)  # Note: np.random.shuffle shuffles the array in-place


original
[1 2 3 4 5]

Reversed array:
[5 4 3 2 1]

Shuffled array:
[3 4 1 5 2]
